### ISSUE TITLE
Seeds gone when planted with long right click

### ISSUE THREAD

**Issue by Knito58** [Resynth-Minecraft-Mod/Resynth-Mod#19]
As right clicking the mineral rock plant does not work I have to destroy the plant, getting the Mineral Rock Shards and the seeds. I had seven of them on 50% soil which were all grown and which I took all. I thought I would replace that seeds quickly with two long right clicks, stroking one time over 4 and the other time over the 3 other soil blocks. This was done in one second. And after this: Where are the plants? Although the planting animation movement of the avatar's hand was shown, the seeds were all lost.

This was the first time that I could replant them all, before there was always only one or two seed which I replaced each on its own.

Resynth 3.1.0 on Forge 28.1.26 for MC 1.14.4

**Comment by Knito58** [comment]
After restarting the game from scratch the seeds are back in the hotbar. I had stopped the game with  the task manager shooting the java engine to maybe avoid auto save.
This is weird. I will close the issue as I cannot tell if it was Forge, Minecraft or Resynth to blame.

**Comment by LMelaia** [comment]
Hey there! Sounds like quite the interesting problem.

Crystalline plants cannot be harvested by right-clicking, so you would have to break them. I could add right-click harvest now that you mention it... we'll see.

Anyway, as for the problems. The seeds disappearing (as I understand it) doesn't completely make sense. It could be a bug with seed placement (however I can't think of anything that would cause it - will check though). It could also be Forge or Minecraft being buggy with client and server communication, where the client didn't register the seeds being planted. I'm not entirely sure myself. It could be that the seeds "got lost" in your inventory, which is why they came back later, however I doubt this. If this happens again, do let me know - it sounds like it could very well be a bug.

You mentioned that after killing the game the seeds appeared back in the hotbar. If you kill Minecraft before it has a chance to save, the world will be unmodified from the previous save (to before you planted the seeds). Minecraft only saves when you: 1. open the escape menu, 2. close the game normally, or 3. autosave on a timing. Because you killed it before it could save. It is possible this is why you got the seeds back.  

Quite a lot of possible causes here and I'm not quite sure myself.

**Comment by Knito58** [comment]
Yep and that is why I closed this. Meanwhile, after saving and backing up the world correctly, I had successfully planted many seeds in long strokes and am not able to redo what happened: Everything just works! Maybe I have a client-server communication problem. Another mod which sometimes derps is the school mod where the used books duplicate when shift-clicked from hotbar into another inventory slot. They are persistent over some open/close inventory GUI attempts. After a minute the duplicates disappear. I'm more convinced it is a Forge problem than anything else. 
The seeds in my OP were really gone and didn't come back while the game was running. And I panicked and shut the game down per task manager.

**Comment by LMelaia** [comment]
Glad to everything is working at least!

I'm pretty sure you don't have any communication problems. It's just a side effect of how Minecraft (and many other games) operates. Both the client and server attempt to do the same thing and only sync up every so often, so they can be out of sync. Other similar issues can also cause this. At least it fixes itself.

Sounds like the School Mod has a bug with shift-clicking in guis. They're pretty common.
