### ISSUE TITLE
Not working and A LOT of console errors for me?

### ISSUE THREAD

**Issue by itsTyrion** [Resynth-Minecraft-Mod/Resynth-Mod#30]
Doesn't work, throws about 3k lines of java stacktraces at start.
Java 8U265 (1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
tested on forge-1.15.2-31.2.30 (min version of another mod I want to use) and forge-1.15.2-31.2.36.
I tried re-downloading, re-installing/updating forge and resynth, using no mods except for resynth..
I don't know how it's possible this is happening for me while working fine for others.
https://hasteb.in/pemuroha.rb

**Comment by LMelaia** [comment]
Hey there! I'm not sure if you've managed to sort the issue out yet or not.

I cannot view the attached log through [Hastebin](https://hastebin.com/). It directs to a new, empty document instead of the logs. Without this I cannot do much other than offer some suggestions.

AFAIK the latest Resynth `1.15` version, `4.2.0`,  should run completely fine by itself and with any mods installed alongside it. At least, heavy testing of the release didn't reveal any problems. As for the large amount of errors spamming the log. This is a known problem that shouldn't cause issues apart from log spam. It's a result of the way Resynth handles plant assets for other mods resources. I haven't found a solution yet either.

### Try the following

It could be possible that:
- A supported mod has changed since support was added, causing plant/seed integration to fail. Try running Resynth without any other mods and see if it starts normally.
- Some unforeseen bug cropped up the newer/newest version. Do older versions work?
- A part, either Minecraft, Forge, Resynth or something else got corrupted. Does Minecraft/Forge run without Resynth loaded?
- Resynth `4.2.0-1.15` was tested using *older versions* of both the Oracle Java JRE & JDK (`JRE 8u211` & `JDK-8u191`) than the version you're using. While *very unlikely*, it's possible it could be a Java version issue.

### Tested on Java:

**Java JRE - 1.8.0_211 (8U211)**, on **Windows 10**
> Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Java JDK - 1.8.0_191 (8U191)**, on **Windows 10**
> Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by LMelaia** [comment]
Some fixes in release 6.0.0. This is an old issues as well with no traction or reason for existing.
