### ISSUE TITLE
[Crash on Load] Seems to look for Waila even if it isn't installed?

### ISSUE THREAD

**Issue by Dragnier** [Resynth-Minecraft-Mod/Resynth-Mod#6]
I use The One Probe instead of Waila.

First line of crash log:
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaDataAccessor

[Full Crash log](https://paste.dimdev.org/zagecipimu.mccrash).

**Comment by LMelaia** [comment]
Thanks for reporting this issue! Yeah it's definitely looking for the hwyla/waila api without checking if it's installed first. Although I'm not sure why off hand. I'll look into it and do some testing on Minecraft installs without hwyla and have the issue fixed in the next version.

I have plans to add The One Probe support so you can expect it in one of the up coming versions.
